### ISSUE TITLE
Mandatory endpoints

### ISSUE THREAD

**Issue by PBharose** [PBharose/Hospital-Management-System#9]
### Discussed in https://github.com/PBharose/NodeJS-Assignment/discussions/8

<div type='discussions-op-text'>

<sup>Originally posted by **PBharose** March 14, 2023</sup>
# Mandatory endpoints
Every API must implement the following mandatory endpoints:

## Health Check
Endpoint URL: **`GET /api/healthcheck`**

Returns:
- 200 if the API is healthy
- 500 otherwise

### Notes:
The health check endpoint should validate that the API is in a healthy status. This is more than 
just returning a 200. For example, it should validate that the key dependencies it's using (a SQL 
Database, a downstream API, etc.) are effectively reachable. This endpoint must be secured, 
otherwise, it could become a source for DDoS attacks on our applications. By convention, we are 
securing it to a role called "HealthCheck".

## Swagger Document
Endpoint URL: **`GET /api/{version}/swagger`**

Returns:
- 200 with the Swagger document in JSON format
</div>

**Comment by PBharose** [comment]
@Rajeshwari-Bhandari Close this issue if completed.

**Comment by Rajeshwari-Bhandari** [comment]
completed
